version: '3.4'
services:
  postgres:
    container_name: ${CONTAINER_NAME:-postgres}
    hostname: ${CONTAINER_NAME:-postgres}
    image: postgres:${PG_VERSION:-16}
    volumes:
      - ./${DATA_FOLDER:-db_data}:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d  # Mounting the init script
      - ./backup:/backup
      - ./archive:/archive
      # - ./dump:/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS:-postgres123}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-dblab}
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - services
    ports:
      - ${PORT:-5432}:5432

    restart: always
  
networks: 
  services:
    external: true
